#!/usr/bin/env python
# -*- coding: utf-8 -*-
# CREATE TABLE Volunteer (id integer primary key, volunteerName varchar(15) not null, volunteerLastName varchar(15) not null, volunteerAddress varchar(30) not null, volunteerCity varchar(10) not null, volunteerZipCode varchar(6) not null, volunteerChurch text not null, volunteerGender varchar(1) not null, volunteerPhone varchar(10) not null, volunteerOccupation text, volunteerChaplain varchar(5) not null, volunteerInterest text, volunteerZone int(1) not null)
import sqlite3
con = sqlite3.connect('ccpr.db')
con.execute("CREATE TABLE Volunteer (id integer primary key, volunteerName varchar(15) not null, volunteerLastName varchar(15) not null, volunteerAddress varchar(30) not null, volunteerCity varchar(10) not null, volunteerZipCode varchar(5) not null, volunteerChurch text not null, volunteerGender varchar(1) not null, volunteerPhone varchar(10) not null, volunteerOccupation text, volunteerChaplain varchar(5) not null, volunteerInterest text, volunteerZone int(1) not null)")
con.execute("CREATE TABLE Prison (id integer primary key, prisonName varchar(20) not null, prisonAddress varchar(30), prisonCity varchar(10) not null, prisonZipCode int(6) not null, prisonGender varchar(1) not null)")
con.execute("CREATE TABLE Prisoner(id integer primary key, prisonerName varchar(20) not null, prisonerGender varchar(1) not null, prisonerZone varchar(1), prisonID int not null, volunteerID int not null, foreign key (prisonID) references Prison(id) on update cascade, foreign key (volunteerID) references Volunteer(id) on update cascade)")
con.execute("CREATE TABLE Visit(id integer primary key, volunteerID int references Volunteer(id) on DELETE CASCADE, prisonID int references Prison(id) on update cascade, visitDay varchar(10) not null, visitHour varchar(8) not null, visitProgram text not null)")
con.execute("CREATE TABLE Period(id integer primary key, periodInitial varchar(10) not null, periodLast varchar(10))")
con.execute("CREATE TABLE Child(id integer primary key, prisonerID int references Prisoner(id) on delete set null, childName varchar(15), childLastName varchar(15), childAge int not null, childGender text not null, childAddress text not null)")
con.execute("CREATE TABLE Position(id integer primary key, positionName varchar(15) not null, posDescription text, posTerms int(1) not null)")
con.execute("CREATE TABLE Board(id integer primary key, periodID int, volunteerID int, positionID int, foreign key (positionID) references `Position`(id) on update cascade, foreign key (volunteerID) references Volunteer(id) on update cascade, foreign key (periodID) references Period(id) on update cascade)")
con.execute("INSERT INTO Volunteer (volunteerName, volunteerLastName, volunteerAddress, volunteerCity, volunteerZipCode, volunteerChurch, volunteerGender, volunteerPhone, volunteerOccupation, volunteerChaplain, volunteerInterest, volunteerZone) VALUES ('Jon', 'Snow', 'Urb. Wall', 'Isabela', '00906', 'MB', 'M', '9398532298', 'Guardia', 'Si', 'Enseñar', 2)")
con.execute("INSERT INTO Volunteer (volunteerName, volunteerLastName, volunteerAddress, volunteerCity, volunteerZipCode, volunteerChurch, volunteerGender, volunteerPhone, volunteerOccupation, volunteerChaplain, volunteerInterest, volunteerZone) VALUES ('Bianca', 'Colon', 'Urb. Sky', 'San Juan', '00926', 'MII', 'F', '7877555555', 'estudiante', 'Si', 'leer', 1)")
con.execute("INSERT INTO Volunteer (volunteerName, volunteerLastName, volunteerAddress, volunteerCity, volunteerZipCode, volunteerChurch, volunteerGender, volunteerPhone, volunteerOccupation, volunteerChaplain, volunteerInterest, volunteerZone) VALUES ('Marta', 'Cortez', 'Urb. Palo Alto', 'Ponce', '00896', 'Protestante', 'F', '7877534569', 'psicologa', 'Si', 'arbol angel', 3)")
con.execute("INSERT INTO Volunteer (volunteerName, volunteerLastName, volunteerAddress, volunteerCity, volunteerZipCode, volunteerChurch, volunteerGender, volunteerPhone, volunteerOccupation, volunteerChaplain, volunteerInterest, volunteerZone) VALUES ('Abi', 'Ayala', 'Urb. Castellana', 'Carolina', '00926', 'Catolica', 'M', '9398588288', 'doctor', 'No', 'operar', 6)")
con.execute("INSERT INTO Volunteer (volunteerName, volunteerLastName, volunteerAddress, volunteerCity, volunteerZipCode, volunteerChurch, volunteerGender, volunteerPhone, volunteerOccupation, volunteerChaplain, volunteerInterest, volunteerZone) VALUES ('Vivian', 'Ayala', '356 Suri', 'Humacao', '00836', 'MI', 'F', '3568588288', 'Programadora', 'No', 'Paginas Web', 4)")
con.execute("INSERT INTO Prison (prisonName, prisonAddress, prisonCity, prisonZipCode, prisonGender) VALUES ('Mostro Verde', 'Ponce Mil', 'Ponce', '00978', 'M')")
con.execute("INSERT INTO Prison (prisonName, prisonAddress, prisonCity, prisonZipCode, prisonGender) VALUES ('Mostra Roja', 'Ponce Mil', 'Ponce', '00978', 'F')")
con.execute("INSERT INTO Prison (prisonName, prisonAddress, prisonCity, prisonZipCode, prisonGender) VALUES ('1072', 'Calle Casio', 'Bayamon', '00976', 'M')")
con.execute("INSERT INTO Prison (prisonName, prisonAddress, prisonCity, prisonZipCode, prisonGender) VALUES ('500', 'Calle Casio', 'Bayamon', '00976', 'F')")
con.execute("INSERT INTO Prison (prisonName, prisonAddress, prisonCity, prisonZipCode, prisonGender) VALUES ('Bayamon 483', 'Calle Casio', 'Bayamon', '00976', 'M')")
con.execute("INSERT INTO Visit (volunteerID, prisonID, visitDay, visitHour, visitProgram) VALUES (1,3, 'martes', '7:00 pm', 'Angel Tree')")
con.execute("INSERT INTO Visit (volunteerID, prisonID, visitDay, visitHour, visitProgram) VALUES (1,4, 'sabados', '10:00 am', 'Discipulado') ")
con.execute("INSERT INTO Visit (volunteerID, prisonID, visitDay, visitHour, visitProgram) VALUES (2,4, 'LMW', '5:00 pm', 'Angel Tree')")
con.execute("INSERT INTO Visit (volunteerID, prisonID, visitDay, visitHour, visitProgram) VALUES (3,4, 'LMW', '5:00 pm', 'Angel Tree')")
con.execute("INSERT INTO Visit (volunteerID, prisonID, visitDay, visitHour, visitProgram) VALUES (5,5, 'J', '5:00 pm', 'Angel Tree')")
con.execute("INSERT INTO Prisoner (prisonerName, prisonerGender, prisonerZone, prisonID, volunteerID) VALUES ('Juan', 'M', 1, 2, 5)")
con.execute("INSERT INTO Prisoner (prisonerName, prisonerGender, prisonerZone, prisonID, volunteerID) VALUES ('Maria', 'F', 2, 3, 3)")
con.execute("INSERT INTO Prisoner (prisonerName, prisonerGender, prisonerZone, prisonID, volunteerID) VALUES ('Marcos', 'M', 5, 4, 2)")
con.execute("INSERT INTO Prisoner (prisonerName, prisonerGender, prisonerZone, prisonID, volunteerID) VALUES ('Rafael', 'M', 4, 4, 1)")
con.execute("INSERT INTO Prisoner (prisonerName, prisonerGender, prisonerZone, prisonID, volunteerID) VALUES ('Miguelina', 'F', 4, 5, 1)")
con.execute("INSERT INTO Child (prisonerID, childName, childLastName, childAge, childGender, childAddress) VALUES (3, 'Liz', 'Lopez', 5, 'F', 'Florida')")
con.execute("INSERT INTO Child (prisonerID, childName, childLastName, childAge, childGender, childAddress) VALUES (4, 'Samantha', 'Rosado', 2, 'F', 'Florida')")
con.execute("INSERT INTO Child (prisonerID, childName, childLastName, childAge, childGender, childAddress) VALUES (2, 'Andrea', 'Rosario', 15, 'F', 'Carolina')")
con.execute("INSERT INTO Child (prisonerID, childName, childLastName, childAge, childGender, childAddress) VALUES (1, 'Juan', 'Lopez', 7, 'M', 'Fajardo')")
con.execute("INSERT INTO Child (prisonerID, childName, childLastName, childAge, childGender, childAddress) VALUES (1, 'Pedro', 'Lopez', 11, 'M', 'Luquillo')")
con.execute("INSERT INTO Position (positionName, posDescription, posTerms) VALUES ('Presidente', 'presentar', 2)")
con.execute("INSERT INTO Position (positionName, posDescription, posTerms) VALUES ('vice-presidente', 'presentar si falta', 2)")
con.execute("INSERT INTO Position (positionName, posDescription, posTerms) VALUES ('secretario', 'apuntar', 3)")
con.execute("INSERT INTO Position (positionName, posDescription, posTerms) VALUES ('SubSecretario', 'presentar', 2)")
con.execute("INSERT INTO Position (positionName, posDescription, posTerms) VALUES ('Tesorero', 'contar', 2)")
con.execute("INSERT INTO Period (periodInitial, periodLast) VALUES ('april 2015', null)")
con.execute("INSERT INTO Period (periodInitial, periodLast) VALUES ('april 2014', 'march 2015')")
con.execute("INSERT INTO Period (periodInitial, periodLast) VALUES ('dic 2012', 'dic 2013')")
con.execute("INSERT INTO Period (periodInitial, periodLast) VALUES ('oct 2011', 'sep 2012')")
con.execute("INSERT INTO Period (periodInitial, periodLast) VALUES ('june', null)")
con.execute("INSERT INTO Board (periodID, volunteerID, positionID) VALUES (1, 1, 1)")
con.execute("INSERT INTO Board (periodID, volunteerID, positionID) VALUES (1, 2, 2)")
con.execute("INSERT INTO Board (periodID, volunteerID, positionID) VALUES (2, 3, 4)")
con.execute("INSERT INTO Board (periodID, volunteerID, positionID) VALUES (2, 5, 2)")
con.execute("INSERT INTO Board (periodID, volunteerID, positionID) VALUES (5, 5, 5)")


con.commit()
